using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using Overrider;

namespace Overrider.Tests
{
    public class OverriderTests
    {
        [Test]
        public void OverrideTest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Override2Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}